Milestone4
saimaAnis21/Calculator-app pull request #3
Opened 2021-06-18 11:59 UTC by saimaAnis21

In this project we did:
1- Logic folder was added
2- calculate.js and operate.js modules were added to the folder
3- calculate.js was added to the App component

2021-06-18 13:42 UTC, Berabjesus requested changes
# Status: CHANGES REQUIRED :warning: :construction: 
Hey @saimaAnis21 👋 
Great start to this milestone. You have implemented most of the specifications required.
### However, you do have a few changes to carry out before we proceed so please take a look at the things you have to work on and their respective review comments below.

- [ ] `calculate.js` uses `button name` argument to mutate `calculator data object` and return its modified version. For instance if button's name == "+/-", it should multiply total and next by -1 to make it negative or positive. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/calculate-mutates-object.png)).
- Currently, your `calculate.js` returns nothing but it should mutate the data and return the total value.

- [ ] `calculate.js` should have some sort of condition to check if the button name is `AC` and handle the corresponding action.
- [ ] `operate.js` has an `operate` function that switches `operation` and uses `plus`, `minus`, `times`, `div` and `modifier` (turning the number into a percentage based number, `e.g. 95 % == .95`) functions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png)). Currently, you have only done that for the `+` operator.
- [ ] [OPTIONAL] In `calculate.js` use ES6 syntax to destructure the prop like this `let { total, next, operation } = dataset;` 

#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-06-18 13:42 UTC, Berabjesus commented on src/logic/calculate.js
> +}
- [ ] Have the `calculate` function return the mutated final total value.

2021-06-18 13:42 UTC, Berabjesus commented on src/logic/calculate.js
> +    operate(total, next, buttonName);
- [ ] The operate function is called but the return value of the `operate` function is not casted into any variable. Please cast the returned value into the appropriate variable.
```
total =  operate(total, next, buttonName)
```

2021-06-19 23:56 UTC, Forison requested changes
# Status::Change Required

### hello @saimaAnis21 

### Good job on addressing the issue raised in the previous review, I think you misunderstood some of the recommendations, kindly check my comments below.

That is it kindly make the change and submit a re-review

#### Happy coding
Addo Forison

2021-06-19 23:56 UTC, Forison commented on src/logic/calculate.js
> +  let { total, next } = calculator;
* [ ] Kindly revert to the old code. The function was not returning anything. all the previous reviewer sought to say is for you to return the mutated calculator object.

2021-06-19 23:56 UTC, Forison commented on src/logic/operate.js
> +      result = nmbrOne / nmbrTwo;
* [ ] Let us handle the division by zero, in this case
result = nmbrTwo === 0 ? 'undefined' : nmbrOne / nmbrTwo;

2021-06-20 11:24 UTC, Forison approved these changes
# Status::Approved✔️

#### Good job on addressing the issues raised, `operate` and `calculate` look good, kindly go ahead and merge the branch and proceed to the next milestone🤗.

#### Happy coding👩‍💻

Addo Forison

2021-06-20 11:43 UTC, merged